package dev.cannoli.ui

const val START_GLYPH = "START"
const val HOLD_START_GLYPH = "HOLD START"
const val SELECT_START_GLYPH = "SELECT + START"
const val SELECT_GLYPH = "SELECT"
const val MENU_GLYPH = "☰"
const val ELLIPSIS = "..."
const val DPAD_HORIZONTAL = "L/R"
const val DPAD_VERTICAL = "U/D"
const val SHOULDERS = "L1/R1"
const val KEY_SHIFT = "⇧"
const val KEY_ENTER = "↵"
const val KEY_BACKSPACE = "←"
const val KEY_SYMBOLS = "⌨"
const val KEY_SPACE = " "

const val STAR = "★"
const val BULLET = "●"
const val HALF_CIRCLE = "◐"
const val CIRCLE_EMPTY = "○"
