package dev.cannoli.igm

data class RaOptionStrings(
    val rootTitle: String = "Settings",
    val on: String = "On",
    val off: String = "Off",
    val restartHint: String = "Applies On Relaunch",
    val savePlatform: String = "Save for Platform",
    val saveGame: String = "Save for this game",
    val dontSave: String = "Discard",
    val resetTitle: String = "Reset Settings",
    val resetPlatform: String = "Reset Platform",
    val resetGame: String = "Reset this game",
    // The core options row. Every other All Settings title comes from RetroArch itself.
    val emulator: String = "Emulator",
    val custom: String = "Custom",
    /** Cannoli's own screen inside the Input category, so not a curated row label. */
    val shortcuts: String = "Shortcuts",
    val buttonMappings: String = "Button Mappings",
    val controllerType: String = "Controller Type",
    /** Formats a Controller Type row when several players have pads. The argument counts from one. */
    val playerController: (Int) -> String = { "Player $it Controller" },
    val shaderApplied: String = "Applied",
    val shaderEnabled: String = "Shader",
    val shaderLoad: String = "Load Preset",
    val shaderAddStart: String = "Add to Start",
    val shaderAddEnd: String = "Add to End",
    val shaderSave: String = "Save Preset",
    /** Formats one pass row. The argument is the pass number, counted from zero. */
    val shaderPass: (Int) -> String = { "Pass $it" },
    /** Formats a pass row that already knows which shader it holds. */
    val shaderPassNamed: (Int, String) -> String = { i, name -> "Pass $i: $name" },
    val shaderParameters: String = "Parameters",
    val shaderPreset: String = "Shader",
    val shaderFilter: String = "Filter",
    val shaderScale: String = "Scale",
    val shaderUnspecified: String = "Unspecified",
    val shaderFilterLinear: String = "Linear",
    val shaderFilterNearest: String = "Nearest",
    /** Formats a scale row. The argument is a whole-number multiple of the input size. */
    val shaderScaleX: (Int) -> String = { "${it}x" },
    val shaderNone: String = "None",
    val infoCore: String = "Core",
    val infoCoreVersion: String = "Core Version",
    val infoRenderer: String = "Renderer",
    val infoContent: String = "ROM",
    val infoSave: String = "Save",
    val infoAchievements: String = "RetroAchievements",
    val achievementsHardcore: String = "Active (Hardcore)",
    val achievementsSoftcore: String = "Active (Softcore)",
    val achievementsUnrecognised: String = "Inactive (Game not recognized)",
    val achievementsNone: String = "Inactive (No achievements)",
    val achievementsOffline: String = "Inactive (Could not reach server)",
    /** Formats the achievements screen's status line when the set came from the offline cache. The
     *  argument is the cache's relative age, such as "3 days ago". */
    val achievementsOfflineCached: (String) -> String = { "Offline - cached $it" },
    val infoGameId: String = "RA Game ID",
    val infoHash: String = "RA Hash",
    val curatedCategoryTitles: Map<String, String> = mapOf(
        CuratedCatalog.CATEGORY_VIDEO to "Video",
        CuratedCatalog.CATEGORY_EMULATOR to "Emulator",
        CuratedCatalog.CATEGORY_ADVANCED to "Advanced",
        CuratedCatalog.CATEGORY_INFO to "Info",
        CuratedCatalog.CATEGORY_OVERLAY to "Overlay",
        CuratedCatalog.CATEGORY_INPUT to "Input",
        CuratedCatalog.CATEGORY_SHADER to "Shaders",
    ),
    val curatedRowLabels: Map<String, String> = mapOf(
        "curated_screen_scaling" to "Screen Scaling",
        "curated_screen_sharpness" to "Screen Sharpness",
        "curated_max_ff_speed" to "Max Fast-Forward Speed",
        "curated_ff_mute" to "Mute on Fast-Forward",
        "curated_rewind" to "Rewind",
        "curated_show_fps" to "Show FPS",
        "curated_debug_hud" to "Debug HUD",
    ),
    val curatedPresetLabels: Map<String, String> = mapOf(
        "scaling_core_reported" to "Core Reported",
        "scaling_integer" to "Integer",
        "scaling_fullscreen" to "Fullscreen",
        "sharpness_sharp" to "Sharp",
        "sharpness_soft" to "Soft",
        "ff_2x" to "2x",
        "ff_4x" to "4x",
        "ff_8x" to "8x",
        "ff_unlimited" to "Unlimited",
        "on" to "On",
        "off" to "Off",
    ),
)
