package dev.cannoli.scorza.launcher

import androidx.test.core.app.ApplicationProvider
import dev.cannoli.scorza.config.CoreInfoRepository
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.File
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * A core's `supported_extensions` is what the core parses, not what it can be handed. RetroArch
 * unpacks archives and resolves m3u playlists first, so refusing on the file's own extension would
 * break a zipped ROM on `snes9x`, which declares no archive format, and multi-disc on the 66 of 83
 * curated cores that never declare `m3u`.
 *
 * The refusal exists for the opposite case: Geolith takes the NeoSD `.neo` format, so a MAME-style
 * Neo Geo romset is content it has no parser for rather than content it fails to load.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class ContentSupportTest {

    private val ctx = ApplicationProvider.getApplicationContext<android.content.Context>()
    private val repo = CoreInfoRepository(ctx.assets).also { it.load() }

    private fun dir(name: String) =
        File(ctx.cacheDir, name).apply { deleteRecursively(); mkdirs() }

    private fun rom(d: File, name: String) = File(d, name).apply { writeText("x") }

    private fun zip(d: File, name: String, vararg inner: String) = File(d, name).apply {
        ZipOutputStream(outputStream()).use { zos ->
            inner.forEach {
                zos.putNextEntry(ZipEntry(it))
                zos.write(ByteArray(64) { 1 })
                zos.closeEntry()
            }
        }
    }

    private fun m3u(d: File, name: String, vararg lines: String) =
        File(d, name).apply { writeText(lines.joinToString("\n") + "\n") }

    private fun check(file: File, core: String) =
        ContentSupport.unsupported(file, repo.getExtensionsFor(core))

    @Test fun `a romset handed to a disc only core`() {
        val d = dir("cs-pcfx")
        assertEquals("zip", check(zip(d, "lbowling.zip", "lbowling/202-c1.c1"), "mednafen_pcfx_libretro"))
    }

    @Test fun `the same file on FinalBurn Neo is fine`() {
        val d = dir("cs-fbneo")
        assertNull(check(zip(d, "lbowling.zip", "lbowling/202-c1.c1"), "fbneo_libretro"))
    }

    // snes9x declares smc|sfc|swc|fig|bs|st and no archive format, yet zipped ROMs are the norm.
    @Test fun `a zipped ROM passes on a core that declares no archive format`() {
        val d = dir("cs-zipped")
        assertNull(check(zip(d, "Mario.zip", "Mario.sfc"), "snes9x_libretro"))
    }

    @Test fun `a plain ROM the core does declare passes`() {
        val d = dir("cs-plain")
        assertNull(check(rom(d, "Mario.sfc"), "snes9x_libretro"))
    }

    @Test fun `a plain ROM for the wrong core is refused`() {
        val d = dir("cs-wrong")
        assertEquals("sfc", check(rom(d, "Mario.sfc"), "gambatte_libretro"))
    }

    // The multi-disc guard. Neither of these cores declares m3u, and both must still launch.
    @Test fun `multi-disc m3u passes on cores that never declare m3u`() {
        val d = dir("cs-m3u")
        val playlist = m3u(d, "FF7.m3u", "FF7 (Disc 1).cue", "FF7 (Disc 2).cue")
        for (core in listOf("yabasanshiro_libretro", "swanstation_libretro")) {
            assertNull("$core refused a multi-disc playlist", check(playlist, core))
        }
    }

    @Test fun `an m3u passes on a core that does declare m3u`() {
        val d = dir("cs-m3u-declared")
        assertNull(check(m3u(d, "FF7.m3u", "FF7 (Disc 1).cue"), "pcsx_rearmed_libretro"))
    }

    // An m3u naming discs the core cannot read is still refused, since resolving is the point.
    @Test fun `an m3u of unreadable discs is refused`() {
        val d = dir("cs-m3u-bad")
        assertEquals("m3u", check(m3u(d, "Game.m3u", "Game (Disc 1).sfc"), "pcsx_rearmed_libretro"))
    }

    @Test fun `comments and blank lines are not the first entry`() {
        val d = dir("cs-m3u-comments")
        val playlist = m3u(d, "FF7.m3u", "# generated by Cannoli", "", "FF7 (Disc 1).cue")
        assertNull(check(playlist, "yabasanshiro_libretro"))
    }

    // The third line on the screen comes from this, so the order has to be the core's own: it
    // leads with the format the core is actually for.
    @Test fun `declared formats keep the order the info gives them`() {
        assertEquals(listOf("cue", "ccd", "toc", "chd"), repo.getExtensionsFor("mednafen_pcfx_libretro"))
        assertEquals(listOf("zip", "7z", "cue", "ccd"), repo.getExtensionsFor("fbneo_libretro"))
    }

    // puae ends its list with a trailing pipe. An empty entry would render as a bare dot.
    @Test fun `a trailing separator does not become an empty format`() {
        for (core in listOf("puae_libretro", "dosbox_pure_libretro")) {
            val exts = repo.getExtensionsFor(core)
            assertEquals("$core has a blank format", emptyList<String>(), exts.filter { it.isBlank() })
        }
    }

    @Test fun `a core that declares nothing never refuses`() {
        val d = dir("cs-unknown")
        assertNull(ContentSupport.unsupported(rom(d, "Mario.sfc"), emptySet()))
    }

    // Never block on a guess: an unreadable or empty archive is let through to fail honestly.
    @Test fun `an unreadable archive is let through`() {
        val d = dir("cs-corrupt")
        assertNull(check(rom(d, "broken.zip"), "mednafen_pcfx_libretro"))
    }

    @Test fun `an extensionless file is let through`() {
        val d = dir("cs-noext")
        assertNull(check(rom(d, "Mario"), "snes9x_libretro"))
    }
}
